/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Compromisso;
import control.ConnectionFactory;
import control.INI;
import control.NivelAcesso;
import control.Usuario;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
import model.CompromissosTableModel;

/**
 *
 * @author wesley.santos
 */
public class AgendaView extends javax.swing.JFrame {

    private Usuario userLogado;
    private static ArrayList<NivelAcesso> niveis = new ArrayList<>();
    public static ArrayList<Compromisso> compromissos = new ArrayList<>();
    private static Connection connection;
    private static ConnectionFactory fabrica = new ConnectionFactory();

    private static CompromissosTableModel modelo = new CompromissosTableModel();
    TableRowSorter<CompromissosTableModel> sorter = new TableRowSorter<CompromissosTableModel>(modelo);
    //pega o caminho da base no arquivo .ini
//    public static INI db;
//    public static INI user;
//    public static INI password;
    public static INI db = new INI("db-config", "local");
    public static INI user = new INI("db-config", "user");
    public static INI password = new INI("db-config", "password");

    /**
     * Creates new form AgendaView
     */
    public AgendaView() throws ClassNotFoundException, SQLException, IOException {
        Usuario u = new Usuario();
        u.setId(4);
        u.setUsuario("ozebe");
        this.userLogado = u;
        initComponents();
        userLabel.setText(this.userLogado.getUsuario());
        //criaTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendario = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCompromissos = new javax.swing.JTable();
        novoBtn = new javax.swing.JButton();
        editarBtn = new javax.swing.JButton();
        excluirBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda de Compromissos");
        setResizable(false);

        calendario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calendarioPropertyChange(evt);
            }
        });

        jLabel1.setText("Usuário:");

        userLabel.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Compromissos do dia");

        tableCompromissos.setModel(modelo);
        tableCompromissos.setRowSorter(sorter);
        tableCompromissos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableCompromissos);

        novoBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        novoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/add.png"))); // NOI18N
        novoBtn.setText("Novo");
        novoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoBtnActionPerformed(evt);
            }
        });
        novoBtn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                novoBtnPropertyChange(evt);
            }
        });

        editarBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/edit.png"))); // NOI18N
        editarBtn.setText("Editar");
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });

        excluirBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        excluirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/remove.png"))); // NOI18N
        excluirBtn.setText("Excluir");
        excluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(novoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(editarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(excluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(calendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendario, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoBtn)
                    .addComponent(editarBtn)
                    .addComponent(excluirBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calendarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_calendarioPropertyChange
        try {
            //rodar comando pegando o dia
            criaTable();
            atualizaDadosTable();
        } catch (ClassNotFoundException | SQLException | IOException ex) {
            Logger.getLogger(AgendaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_calendarioPropertyChange

    private void novoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoBtnActionPerformed

        final NovoCompromissoView novoCompromisso = new NovoCompromissoView(calendario.getDate(), userLogado);
        novoCompromisso.setVisible(rootPaneCheckingEnabled);
        this.novoBtn.setEnabled(false);
//        try {
//            carregaNiveisAcesso();
//            final UsuarioNovoView novoUsuario = new UsuarioNovoView(niveis);
//            novoUsuario.setVisible(true);
//            this.novoBtn.setEnabled(false);
//        } catch (ClassNotFoundException | SQLException | IOException ex) {
//            JOptionPane.showMessageDialog(null, "Não foi possível carregar!\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
//            Logger.getLogger(UsuariosView.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_novoBtnActionPerformed

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
        int linha = -1;
        linha = tableCompromissos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Favor selecionar um compromisso", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            linha = tableCompromissos.getRowSorter().convertRowIndexToModel(linha);
            System.out.println("h -> " + compromissos.get(linha).getHora() + " id -> " + compromissos.get(linha).getId());
        }
//        try {
//            carregaNiveisAcesso();
//            int linha = -1;
//            linha = tableCompromissos.getSelectedRow();
//            if (linha == -1) {
//                JOptionPane.showMessageDialog(null, "Favor selecionar um compromisso", "Erro", JOptionPane.ERROR_MESSAGE);
//            } else {
//                linha = tableCompromissos.getRowSorter().convertRowIndexToModel(linha);
//                editarBtn.setEnabled(false);
//                final UsuariosEditaView editaUsuario = new UsuariosEditaView(usuarios.get(linha), niveis);
//                editaUsuario.setVisible(true);
//            }
//        } catch (ClassNotFoundException | SQLException | IOException ex) {
//            JOptionPane.showMessageDialog(null, "Não foi possível carregar!\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
//        } catch (IllegalArgumentException ex) {
//            JOptionPane.showMessageDialog(null, "Não foi possível carregar o compromisso do usuário!\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
//            editarBtn.setEnabled(true);
//        }

    }//GEN-LAST:event_editarBtnActionPerformed

    private void excluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirBtnActionPerformed
        int linha = -1;
        linha = tableCompromissos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Favor selecionar um compromisso", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            linha = tableCompromissos.getRowSorter().convertRowIndexToModel(linha);
            //System.out.println("h -> " + compromissos.get(linha).getHora() + " id -> " + compromissos.get(linha).getId());
            excluirCompromisso(compromissos.get(linha).getId());
        }
    }//GEN-LAST:event_excluirBtnActionPerformed

    private void novoBtnPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_novoBtnPropertyChange
        try {
            criaTable();
            atualizaDadosTable();
        } catch (ClassNotFoundException | SQLException | IOException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível carregar!\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(AgendaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_novoBtnPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AgendaView().setVisible(true);
                } catch (ClassNotFoundException | SQLException | IOException ex) {
                    JOptionPane.showMessageDialog(null, "Não foi possível carregar!\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(AgendaView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.toedter.calendar.JCalendar calendario;
    public static javax.swing.JButton editarBtn;
    public static javax.swing.JButton excluirBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JButton novoBtn;
    private javax.swing.JTable tableCompromissos;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables

    public void criaTable() throws ClassNotFoundException, SQLException, IOException {
        connection = fabrica.getConnection(db.getDir(), user.getDir(), password.getDir());

        PreparedStatement stmt = connection.prepareStatement("select * from compromisso as c where c.data_comp = ? and c.idusuario = ? order by c.hora ");

        java.sql.Date sDate = convertUtilToSql(calendario.getDate());
        stmt.setDate(1, sDate);
        stmt.setInt(2, this.userLogado.getId());
        ResultSet resultSet = stmt.executeQuery();

//        while (modelo.getRowCount() > 0) {
//            for (int i = 0; i < modelo.getRowCount(); i++) {
//                modelo.removeUsuario(i);
//            }
//        }
        compromissos.removeAll(compromissos);

        while (resultSet.next()) {
            Compromisso c = new Compromisso();

            c.setCriado(formataTimestamp(resultSet.getTimestamp("criado")));
            c.setData(resultSet.getString("data_comp"));
            c.setDescricao(resultSet.getString("descricao"));
            c.setEditado(formataTimestamp(resultSet.getTimestamp("editado")));
            c.setHora(resultSet.getString("hora"));
            c.setId(resultSet.getInt("id"));
            c.setIdUsuario(resultSet.getInt("idUsuario"));

            modelo.addCompromisso(c);
            compromissos.add(c);
        }
        resultSet.close();
        stmt.close();
        connection.close();
    }

    public static void atualizaDadosTable() {
        while (modelo.getRowCount() > 0) {
            for (int i = 0; i < modelo.getRowCount(); i++) {
                modelo.removeCompromisso(i);
            }
        }
        java.sql.Date sDate = convertUtilToSql(calendario.getDate());

        for (Compromisso c : compromissos) {
            if (c.getData().equals(sDate.toString())) {
                modelo.addCompromisso(c);
            }

        }
    }

    private static java.sql.Date convertUtilToSql(java.util.Date uDate) {
        java.sql.Date sDate = new java.sql.Date(uDate.getTime());
        return sDate;
    }

    private static String formataTimestamp(Timestamp t) {
        if (t != null) {
            SimpleDateFormat formatador = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
            return formatador.format(t);
        } else {
            return "";
        }

    }

    private void excluirCompromisso(int id) {
        try {
            connection = fabrica.getConnection(db.getDir(), user.getDir(), password.getDir());

            PreparedStatement stmt = connection.prepareStatement("delete from compromisso as c where c.id = ?");
            stmt.setInt(1, id);

            stmt.executeUpdate();
            stmt.close();
            connection.close();
            criaTable();
            atualizaDadosTable();
            JOptionPane.showMessageDialog(null, "Compromisso excluído!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        } catch (ClassNotFoundException | SQLException | IOException ex) {
            Logger.getLogger(AgendaView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Não foi possível excluir!\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);

        }
    }

    public static void carregaNiveisAcesso() throws ClassNotFoundException, SQLException, IOException {
        connection = fabrica.getConnection(db.getDir(), user.getDir(), password.getDir());
        PreparedStatement stmt = connection.prepareStatement("select * from nivelAcesso order by nivelAcesso.id");
        ResultSet resultSet = stmt.executeQuery();
        niveis.removeAll(niveis);
        while (resultSet.next()) {
            NivelAcesso nv = new NivelAcesso();
            nv.setId(resultSet.getInt("id"));
            nv.setDescricao(resultSet.getString("descricao"));
            nv.setSigla(resultSet.getString("sigla"));
            niveis.add(nv);
        }
        resultSet.close();
        stmt.close();
        connection.close();
    }

}
